[package]
name = "fibonacci"
version = "1.0.0"
authors = ["dcervi <dave@codescreen.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "fibonacci"
path = "src/fibonacci.rs"
